// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hkkthuaazrwkkurvpram.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhra3RodWFhenJ3a2t1cnZwcmFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyMjU4NDAsImV4cCI6MjA1ODgwMTg0MH0.vrwaez4MiGjyXfNsMaMNMEEH00yWD-FXXN9-CikZj7k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);