
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzhumokfzucpzrffhbgz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6aHVtb2tmenVjcHpyZmZoYmd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMTkxNDQsImV4cCI6MjA1OTY5NTE0NH0.-t46in0WDWQaTEnkGEhJ6aJSpiVuYpsrSsW5WvuHjvY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
